[package]
name = "rustier-chess"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_derive = "1.0.217"
serde = "1.0.217"
bincode = "1.3.3"

[dev-dependencies]
once_cell = "1.20.2"
itertools = "0.14.0"

[[bench]]
name = "move_generation"
harness = false
